import type { Restaurant } from "./domain";

export const RESTAURANTS: readonly Restaurant[] = [
  {
    id: "miso-main",
    name: "Miso & Main",
    initials: "M+M",
    cuisine: "Japanese",
    description: "Donburi, crisp katsu, and house teas from a tiny 12th Street counter.",
    address: "East 12th Street",
    walkMinutes: 7,
    hasOrderedBefore: true,
    accent: "#ff7a45",
    basketName: "Salmon don lunch",
    basketItems: ["Miso salmon don", "Cucumber sunomono", "Iced hojicha"],
    quotes: [
      {
        id: "miso-direct",
        channel: {
          kind: "direct",
          name: "Restaurant site",
          shortName: "RS",
          provider: "Toast",
        },
        itemsSubtotalCents: 2150,
        feesCents: 0,
        taxCents: 190,
        publicDiscountCents: 300,
        publicOffer: "$3 weekday lunch",
        offerCondition: " Automatically applied before 3 PM.",
        freshnessMinutes: 3,
        confidence: "exact",
      },
      {
        id: "miso-doordash",
        channel: {
          kind: "doordash",
          name: "DoorDash",
          shortName: "DD",
        },
        itemsSubtotalCents: 2290,
        feesCents: 99,
        taxCents: 203,
        publicDiscountCents: 0,
        freshnessMinutes: 5,
        confidence: "exact",
      },
      {
        id: "miso-uber",
        channel: {
          kind: "uber-eats",
          name: "Uber Eats",
          shortName: "UE",
        },
        itemsSubtotalCents: 2340,
        feesCents: 129,
        taxCents: 207,
        publicDiscountCents: 0,
        personalOffer: { label: "$5 account offer", discountCents: 500 },
        offerCondition: " Demo account offer; $20 minimum met.",
        freshnessMinutes: 7,
        confidence: "estimated",
      },
    ],
  },
  {
    id: "greenline-falafel",
    name: "Greenline Falafel",
    initials: "GF",
    cuisine: "Mediterranean",
    description: "Charred shawarma, lemony grains, and serious pickles near Irving Place.",
    address: "Irving Place",
    walkMinutes: 9,
    hasOrderedBefore: false,
    accent: "#c7e65b",
    basketName: "Shawarma bowl",
    basketItems: ["Chicken shawarma bowl", "Spicy tahini", "Mint lemonade"],
    quotes: [
      {
        id: "greenline-direct",
        channel: {
          kind: "direct",
          name: "Restaurant site",
          shortName: "RS",
          provider: "Square",
        },
        itemsSubtotalCents: 1595,
        feesCents: 0,
        taxCents: 141,
        publicDiscountCents: 0,
        freshnessMinutes: 2,
        confidence: "exact",
      },
      {
        id: "greenline-doordash",
        channel: {
          kind: "doordash",
          name: "DoorDash",
          shortName: "DD",
        },
        itemsSubtotalCents: 1645,
        feesCents: 49,
        taxCents: 146,
        publicDiscountCents: 300,
        publicOffer: "$3 pickup promo",
        offerCondition: " Public pickup offer; $15 minimum met.",
        freshnessMinutes: 4,
        confidence: "exact",
      },
      {
        id: "greenline-uber",
        channel: {
          kind: "uber-eats",
          name: "Uber Eats",
          shortName: "UE",
        },
        itemsSubtotalCents: 1745,
        feesCents: 0,
        taxCents: 155,
        publicDiscountCents: 0,
        personalOffer: { label: "$5 account offer", discountCents: 500 },
        offerCondition: " Demo account offer for this storefront.",
        freshnessMinutes: 6,
        confidence: "exact",
      },
    ],
  },
  {
    id: "seventh-street-slice",
    name: "Seventh Street Slice",
    initials: "7S",
    cuisine: "Pizza",
    description: "Big foldable slices, blistered square pies, and no unnecessary ceremony.",
    address: "East 7th Street",
    walkMinutes: 12,
    hasOrderedBefore: true,
    accent: "#ffd15b",
    basketName: "Two-slice run",
    basketItems: ["Classic cheese slice", "Pepperoni square", "Sparkling water"],
    quotes: [
      {
        id: "slice-direct",
        channel: {
          kind: "direct",
          name: "Restaurant site",
          shortName: "RS",
          provider: "ChowNow",
        },
        itemsSubtotalCents: 1325,
        feesCents: 0,
        taxCents: 117,
        publicDiscountCents: 0,
        freshnessMinutes: 1,
        confidence: "exact",
      },
      {
        id: "slice-doordash",
        channel: {
          kind: "doordash",
          name: "DoorDash",
          shortName: "DD",
        },
        itemsSubtotalCents: 1450,
        feesCents: 75,
        taxCents: 129,
        publicDiscountCents: 0,
        freshnessMinutes: 8,
        confidence: "estimated",
      },
      {
        id: "slice-uber",
        channel: {
          kind: "uber-eats",
          name: "Uber Eats",
          shortName: "UE",
        },
        itemsSubtotalCents: 1495,
        feesCents: 99,
        taxCents: 133,
        publicDiscountCents: 0,
        personalOffer: { label: "$3 repeat-order offer", discountCents: 300 },
        offerCondition: " Demo account offer; expires tonight.",
        freshnessMinutes: 5,
        confidence: "exact",
      },
    ],
  },
  {
    id: "bengal-tiger-club",
    name: "Bengal Tiger Club",
    initials: "BT",
    cuisine: "Indian",
    description: "Slow-cooked curries, smoky kebabs, and bright chutneys just off Broadway.",
    address: "East 18th Street",
    walkMinutes: 14,
    hasOrderedBefore: false,
    accent: "#b7a6ff",
    basketName: "Curry night for one",
    basketItems: ["Chicken makhani", "Garlic naan", "Cucumber raita"],
    quotes: [
      {
        id: "bengal-direct",
        channel: {
          kind: "direct",
          name: "Restaurant site",
          shortName: "RS",
          provider: "Custom checkout",
        },
        itemsSubtotalCents: 2000,
        feesCents: 0,
        taxCents: 177,
        publicDiscountCents: 200,
        publicOffer: "Direct-order savings",
        offerCondition: " $2 automatically applied to online pickup.",
        freshnessMinutes: 4,
        confidence: "exact",
      },
      {
        id: "bengal-doordash",
        channel: {
          kind: "doordash",
          name: "DoorDash",
          shortName: "DD",
        },
        itemsSubtotalCents: 2140,
        feesCents: 0,
        taxCents: 190,
        publicDiscountCents: 0,
        personalOffer: { label: "$4 account offer", discountCents: 400 },
        offerCondition: " Demo account pickup offer.",
        freshnessMinutes: 6,
        confidence: "exact",
      },
      {
        id: "bengal-uber",
        channel: {
          kind: "uber-eats",
          name: "Uber Eats",
          shortName: "UE",
        },
        itemsSubtotalCents: 2190,
        feesCents: 79,
        taxCents: 194,
        publicDiscountCents: 300,
        publicOffer: "$3 pickup savings",
        offerCondition: " Public storefront promotion.",
        freshnessMinutes: 9,
        confidence: "estimated",
      },
    ],
  },
  {
    id: "casa-nopal",
    name: "Casa Nopal",
    initials: "CN",
    cuisine: "Mexican",
    description: "Pressed-to-order tortillas, citrusy carnitas, and punchy green salsa.",
    address: "East 4th Street",
    walkMinutes: 16,
    hasOrderedBefore: false,
    accent: "#63d7c4",
    basketName: "Carnitas taco set",
    basketItems: ["Three carnitas tacos", "Esquites", "Hibiscus agua fresca"],
    quotes: [
      {
        id: "nopal-direct",
        channel: {
          kind: "direct",
          name: "Restaurant site",
          shortName: "RS",
          provider: "Toast",
        },
        itemsSubtotalCents: 1750,
        feesCents: 0,
        taxCents: 155,
        publicDiscountCents: 0,
        freshnessMinutes: 3,
        confidence: "exact",
      },
      {
        id: "nopal-doordash",
        channel: {
          kind: "doordash",
          name: "DoorDash",
          shortName: "DD",
        },
        itemsSubtotalCents: 1850,
        feesCents: 99,
        taxCents: 164,
        publicDiscountCents: 400,
        publicOffer: "$4 pickup promo",
        offerCondition: " Public offer on baskets over $18.",
        freshnessMinutes: 5,
        confidence: "exact",
      },
      {
        id: "nopal-uber",
        channel: {
          kind: "uber-eats",
          name: "Uber Eats",
          shortName: "UE",
        },
        itemsSubtotalCents: 1850,
        feesCents: 0,
        taxCents: 164,
        publicDiscountCents: 0,
        personalOffer: { label: "$6 account offer", discountCents: 600 },
        offerCondition: " Demo account promotion; one use remaining.",
        freshnessMinutes: 6,
        confidence: "exact",
      },
    ],
  },
  {
    id: "parkside-deli",
    name: "Parkside Deli",
    initials: "PD",
    cuisine: "Sandwiches",
    description: "Overstuffed sandwiches, crunchy pickles, and excellent counter coffee.",
    address: "Gramercy Park North",
    walkMinutes: 18,
    hasOrderedBefore: true,
    accent: "#80b8ff",
    basketName: "Turkey club lunch",
    basketItems: ["Turkey club", "Sea-salt chips", "Cold brew"],
    quotes: [
      {
        id: "parkside-direct",
        channel: {
          kind: "direct",
          name: "Restaurant site",
          shortName: "RS",
          provider: "Square",
        },
        itemsSubtotalCents: 1685,
        feesCents: 50,
        taxCents: 149,
        publicDiscountCents: 0,
        freshnessMinutes: 2,
        confidence: "exact",
      },
      {
        id: "parkside-doordash",
        channel: {
          kind: "doordash",
          name: "DoorDash",
          shortName: "DD",
        },
        itemsSubtotalCents: 1795,
        feesCents: 0,
        taxCents: 159,
        publicDiscountCents: 0,
        freshnessMinutes: 7,
        confidence: "estimated",
      },
      {
        id: "parkside-uber",
        channel: {
          kind: "uber-eats",
          name: "Uber Eats",
          shortName: "UE",
        },
        itemsSubtotalCents: 1745,
        feesCents: 79,
        taxCents: 155,
        publicDiscountCents: 0,
        personalOffer: { label: "$4 account offer", discountCents: 400 },
        offerCondition: " Demo account offer for pickup orders.",
        freshnessMinutes: 8,
        confidence: "exact",
      },
    ],
  },
] as const;
